# Generated by Django 2.2.4 on 2019-08-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_customflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stateobjectrelation',
            name='waiting',
            field=models.BooleanField(default=False),
        ),
    ]
